title: Insert Site Title
email: your-email@example.com
github_username:  davidewarren

repos:
- name: federalist-guide-template
  description: Main repository
  url: https://github.com/davidewarren/federalist-guide-template

collections:
  pages:
    output: true
    permalink: /:path/

expand_nav: true
navigation:
- text: Overview
  url: /overview/
  internal: true
- text: Getting Started
  url: /getting-started/
  internal: true
 
 # Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
