title: Insert Site Title
email: your-email@example.com
github_username:  davidewarren

repos:
- name: test repo
  description: Main repository
  url: https://github.com/davidewarren/federalist-guide-template

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Navigation and Sidebar
expand_nav: true
navigation:
- text: Overview
  internal: true
- text: Getting Started
  url: pages/getting-started
  internal: true
- text: Background
  url: getting-started/
  internal: true
 
 # Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
